# Generated by Django 4.2.4 on 2023-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
