# Generated by Django 4.2.4 on 2023-08-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_deck_user_alter_card_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
    ]
